/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_main_tflmodelruntimeevaluation_RuntimeEvaluation */

#ifndef _Included_com_main_tflmodelruntimeevaluation_RuntimeEvaluation
#define _Included_com_main_tflmodelruntimeevaluation_RuntimeEvaluation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_main_tflmodelruntimeevaluation_RuntimeEvaluation
 * Method:    runtimeEvaluate
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jdouble JNICALL Java_com_main_tflmodelruntimeevaluation_RuntimeEvaluation_runtimeEvaluate
  (JNIEnv *env, jclass clazz, jstring path, jstring cachePath);

//JNIEXPORT jstring JNICALL
//Java_com_main_tflmodelruntimeevaluation_RuntimeEvaluation_getSocName(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
